# Generated by Django 5.2.11 on 2026-02-17 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('annual_fee_cents', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bank', 'name'],
                'unique_together': {('bank', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BenefitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount_cents', models.IntegerField()),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=20)),
                ('period_type', models.CharField(choices=[('calendar_year', 'Calendar Year'), ('membership_year', 'Membership Year')], max_length=20)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('dining', 'Dining'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('transportation', 'Transportation'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='cards.cardtemplate')),
            ],
            options={
                'ordering': ['card_template', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_amount_cents', models.IntegerField(blank=True, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_benefits', to='cards.benefittemplate')),
            ],
            options={
                'ordering': ['user_card', 'benefit_template'],
            },
        ),
        migrations.CreateModel(
            name='BenefitUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField()),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='cards.userbenefit')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField()),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to='cards.cardtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userbenefit',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='cards.usercard'),
        ),
    ]
