# Generated by Django 5.2.11 on 2026-02-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='credit_limit_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
