# Generated by Django 5.2.11 on 2026-02-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_usercard_credit_limit_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='card_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=20),
        ),
    ]
